# Configuration version
VERSION: 1

# Reproducibility and device
RANDOM_SEED: 42
DEVICE: cuda

# Graph matching solver
SOLVER: greedy

# Output file name
OUTFILE: magna_ppi_v1

# Dataset
DATA:
  PATH: data/ppi
  SIZE: 5
  TRAIN_RATIO: 0.2
  P_ADD:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  P_RM:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25

MODEL:
  NAME: MAGNA
  MEASURE: S3
  POPULATION_SIZE: 15000
  NUM_GENERATIONS: 2000