# Reproducibility and device
SEED: 42
DEVICE: cuda
TEST: robustness

OUTFILE: sigma_edi3_v1.csv

# Dataset
DATA:
  NAME: edi3
  SUBSET: [edi3]
  NUM_COPIES: 5
  PATH: data/edi3
  P_ADD:
    - 0.00
  P_RM:
    - 0.20
  TRAIN_RATIO: 0.2
  VAL_RATIO: 0.0
  GT_MODE: matrix

# Model & Training
MODEL:
  NAME: sigma
  NODE_FEATURE_DIM: 1
  EMBEDDING_DIM: 256
  T: 5
  MISS_MATCH_VALUE: 0.01
  TAU: 1.0
  N_SINK_ITERS: 10
  N_SAMPLES: 10

TRAIN:
  LR: 1.e-4
  L2NORM: 1.e-4
  EPOCHS: 100

MATCHER: greedy
VERSION: 1