# Reproducibility and device
RANDOM_SEED: 42
DEVICE: cuda

# Dataset
DATA:
  SIZE: 10
  PATH: data/edi3
  P_ADD:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  P_RM:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  TRAIN_RATIO: 0.2

# Model & Training
MODEL:
  NAME: sigma
  NODE_FEATURE_DIM: 1
  EMBEDDING_DIM: 32
  T: 5
  MISS_MATCH_VALUE: 0.01
  TAU: 1.0
  N_SINK_ITERS: 10
  N_SAMPLES: 10

TRAIN:
  LR: 1.e-4
  L2NORM: 1.e-4
  EPOCHS: 100

MATCHER: greedy
VERSION: 1