# Reproducibility and device
RANDOM_SEED: 42
DEVICE: cuda

MATCHER: greedy
VERSION: 1

# Dataset
DATA:
  SIZE: 10
  PATH: data/edi3
  P_ADD:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  P_RM:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  TRAIN_RATIO: 0.2

# Model & Training
MODEL:
  NAME: ar_gine_mlp
  NODE_FEATURE_INIT: share
  NODE_FEATURE_DIM: 1
  HIDDEN_DIM: None
  EMBEDDING_DIM: 256
  NUM_LAYERS: 2

TRAIN:
  EMBEDDING:
    LR: 1.e-4
    L2NORM: 0
    EPOCHS: 1000
  MAPPING:
    LR: 0.01
    L2NORM: 0
    EPOCHS: 100