# Reproducibility and device
RANDOM_SEED: 42
DEVICE: cpu

# Dataset
DATA:
  SIZE: 5
  PATH: data/edi3
  P_ADD:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  P_RM:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  TRAIN_RATIO: 0.8

# Model & Training
MODEL:
  NAME: tau

GINE:
  NODE_FEATURE_DIM: 1
  EMBEDDING_DIM: 4
  NUM_LAYERS: 2
  BIAS: True

TRAIN:
  LR: 1.e-4
  L2NORM: 1.e-4
  EPOCHS: 100


MATCHER: greedy
VERSION: 1