# Reproducibility & Version
SEED: 42
VERSION: 1

# Test type
TEST: robustness

# Dataset
DATA:
  NAME: edi3
  PATH: data/edi3
  SUBSET: ['edi3']
  TRAIN_RATIO: 0.15
  VAL_RATIO: 0.15
  NUM_COPIES: 20
  GT_MODE: matrix
  P_ADD:
    - 0.0
  P_RM:
    - 0.05

# Model
MODEL: 
  NAME: shelley

INIT:
  FEATURES: share
  FEATURE_DIM: 1

EMBEDDING:
  MODEL: gine2
  IN_CHANNELS: 1
  DIM: 512
  OUT_CHANNELS: 512
  NUM_CONV_LAYERS: 3

MATCHING:
  MODEL: sgm
  N_SINK_ITERS: 10
  BETA: 0.001
  TAU: 1.0
  MASK: True

# Training
TRAIN:
  OPTIMIZER: adam
  LR: 0.00001
  L2NORM: 0.0
  EPOCHS: 1000
  PATIENCE: 20
