# Reproducibility & Version
SEED: 42
VERSION: 1

# Test type
TEST: robustness

# Dataset
DATA:
  NAME: edi3
  PATH: data/edi3
  SUBSET: ['edi3']
  TRAIN_RATIO: 0.15
  VAL_RATIO: 0.15
  NUM_COPIES: 20
  GT_MODE: matrix
  P_ADD:
    - 0.0
  P_RM:
    - 0.2

# Model
MODEL: 
  NAME: shelley

INIT:
  FEATURES: share
  FEATURE_DIM: 1

EMBEDDING:
  MODEL: gine2
  IN_CHANNELS: 1
  DIM: 256
  OUT_CHANNELS: 256
  NUM_CONV_LAYERS: 2

MATCHING:
  MODEL: linear
  EMBEDDING_DIM: 256

# Training
TRAIN:
  OPTIMIZER: adam
  LR: 0.00001
  L2NORM: 0.0
  EPOCHS: 1000
  PATIENCE: 20
