# Reproducibility & Version
SEED: 42
VERSION: 1

# Test type
TEST: robustness

# Dataset
DATA:
  NAME: edi3
  PATH: data/edi3
  SUBSET: ['edi3']
  TRAIN_RATIO: 0.15
  VAL_RATIO: 0.15
  NUM_COPIES: 20
  GT_MODE: matrix
  P_ADD:
    - 0.0
  P_RM:
    - 0.25

# Model
MODEL: 
  NAME: shelley

INIT:
  FEATURES: share
  FEATURE_DIM: 1

EMBEDDING:
  MODEL: gcn
  IN_CHANNELS: 1
  HIDDEN_CHANNELS: 64
  OUT_CHANNELS: 32
  NUM_LAYERS: 5

MATCHING:
  MODEL: msgm
  N_SINK_ITERS: 10
  BETA: 0.001

# Training
TRAIN:
  OPTIMIZER: adam
  LR: 0.00001
  L2NORM: 0.0001
  EPOCHS: 1000
  PATIENCE: 20
