RANDOM_SEED: 42
DEVICE: cuda
MATCHER: greedy
VERSION: 1

# Dataset
DATA:
  SIZE: 10
  PATH: data/edi3
  P_ADD:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  P_RM:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  TRAIN_RATIO: 0.2

# Model & Training
MODEL:
  NAME: shelley

EMBEDDING:
  MODEL: share
  NODE_FEATURE_DIM: 300
  EMBEDDING_DIM: 300
  OPTIMIZER: None


MAPPING:
  MODEL: linear
  NORMALIZE: True
  BIAS: True

  OPTIMIZER: Adam
  LOSS_FN: euclidean
  LR: 0.01
  L2NORM: 0.0
  BATCH_SIZE: 8
  EPOCHS: 100
