RANDOM_SEED: 42
DEVICE: cuda
MATCHER: greedy
VERSION: 1

# Dataset
DATA:
  SIZE: 10
  PATH: data/edi3
  P_ADD:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  P_RM:
    - 0.00
    - 0.05
    - 0.10
    - 0.20
    - 0.25
  TRAIN_RATIO: 0.2

# Model & Training
MODEL:
  NAME: shelley

EMBEDDING:
  MODEL: pale
  NEG_SAMPLE_SIZE: 10 
  EMBEDDING_DIM: 300
  EMBEDDING_NAME: ''

  OPTIMIZER: Adam
  LR: 0.01
  L2NORM: 0.0
  BATCH_SIZE: 512
  EPOCHS: 1000

MAPPING:
  MODEL: gcn
  IN_CHANNELS: 300
  HIDDEN_CHANNELS: 0
  OUT_CHANNELS: 32
  NUM_LAYERS: 1
  NORMALIZE: True
  BIAS: True

  OPTIMIZER: Adam
  LOSS_FN: bcewithlogits
  LR: 1.e-4
  L2NORM: 1.e-4
  EPOCHS: 100
